// Generated by https://quicktype.io

declare interface IBuildData {
    project: string;
    cmd: IBuildAction[];
}

declare interface IBuildAction {
    type: string;
    name: string;
    path: string;
    cmd: string;
    encoding: string;
    debug: boolean;
}


// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"


// .\TexturePacker.exe D:\1\ --format json --sheet d:\1\1.png --data d:\1\1.json

declare interface TPData {
    frames: { [key: string]: TPFrameValue };
    meta:   TPMeta;
}

declare interface TPFrameValue {
    frame:            TPSpriteSourceSizeClass;
    rotated:          boolean;
    trimmed:          boolean;
    spriteSourceSize: TPSpriteSourceSizeClass;
    sourceSize:       TPSize;
}

declare interface TPSpriteSourceSizeClass {
    x: number;
    y: number;
    w: number;
    h: number;
}

declare interface TPSize {
    w: number;
    h: number;
}

declare interface TPMeta {
    app:         string;
    version:     string;
    image:       string;
    format:      string;
    size:        TPSize;
    scale:       string;
    smartupdate: string;
}
